name: e_commerce
description: "E-commerce Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  image_picker: ^0.8.5+3
  flutter_svg: ^1.0.3
  dio: ^5.0.3 
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  searchfield: ^1.2.2
  custom_rating_bar: ^3.0.0
  easy_stepper: ^0.8.5+1
  order_tracker: ^0.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/icons/
    - assets/image/
